---
title: "visualization"
author: "Wenzhao Wu"
date: "10/5/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 1,
  out.width = "90%"
)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```

# Basic scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

# Advanced scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5) +
  geom_smooth(se = FALSE)
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
weather_df %>%
  mutate(
    tmin = 9 * tmin / 5 + 32,
    tmax = 9 * tmax / 5 + 32
  )

centralpark = 
  subset(weather_df, name %in% ("CentralPark_NY"))

ggplot(centralpark,aes(x = tmax, y = tmin, color = name)) + 
  geom_point() +
  geom_smooth(se = FALSE, color = "blue")
```

# Odds and ends

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")

ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue"))
```

# Univariate plots

```{r}
ggplot(weather_df, aes(x = tmax)) + 
  geom_histogram()
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = 0.4, color = "blue") +
  geom_rug()
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_boxplot()
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue")
```

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

# Assessment

```{r}
ggplot(weather_df, aes(x = prcp, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 5, breaks = seq(0,945,50)) +
  scale_y_continuous(
    trans = "sqrt")

ggplot(weather_df, aes(x = prcp, fill = name)) + 
  geom_density(alpha = .4, adjust = 0.4, color = "yellow") +
  scale_y_continuous(
    trans = "sqrt")

ggplot(weather_df, aes(x = name, y = prcp)) + 
  geom_boxplot(outlier.shape = 5, outlier.size = 1) +
  scale_y_continuous(
    trans = "sqrt")

ggplot(weather_df, aes(x = name, y = prcp)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue") +
  scale_y_continuous(
    trans = "sqrt")

ggplot(weather_df, aes(x = prcp, y = name)) + 
  geom_density_ridges(scale = .85)
```

# Saving and embedding plots

```{r}
weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("weather_plot.pdf", weather_plot, width = 8, height = 5)
```

```{r fig.width = 6,fig.asp = 1}
weather_plot
```

